enum 50100 "Data Type"
{
    Extensible = true;

    value(0; Customer)
    {
        Caption = 'Customer';
    }

    value(1; Vendor)
    {
        Caption = 'Vendor';
    }

    value(2; GLAccount)
    {
        Caption = 'G/L Account';
    }

    value(3; Item)
    {
        Caption = 'Item';
    }

    value(4; Dimension)
    {
        Caption = 'Dimension';
    }

    value(5; DimensionValue)
    {
        Caption = 'Dimension Value';
    }
}